/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LabelTemplate } from "./types";

export const LABEL_TEMPLATES: LabelTemplate[] = [
  {
    name: "Tem kệ siêu thị (Thực phẩm tươi sống)",
    description: "Mẫu tem kệ siêu thị tiêu chuẩn 65x45mm dùng cho thực phẩm đông lạnh, tươi sống có giá bán, barcode, trọng lượng và thông tin hạn sử dụng.",
    config: {
      width: 65,
      height: 45,
      name: "Tem kệ siêu thị",
      bgColor: "#ffffff"
    },
    objects: [
      {
        id: "text-title",
        type: "text",
        x: 0,
        y: -19,
        width: 61,
        height: 6,
        content: "MÁ ĐÙI GÀ CP",
        fontSize: 14,
        fontWeight: "bold",
        fontFamily: "Inter",
        textAlign: "center",
        excelColumn: "Tên hàng",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "barcode-main",
        type: "barcode",
        x: -29,
        y: -14,
        width: 28,
        height: 17,
        barcodeHeight: 12,
        content: "2510003000016",
        displayValue: true,
        barcodeFormat: "CODE128",
        excelColumn: "Mã vạch",
        isCenterRelative: true,
        textFlowOrigin: "center",
        barcodeFontSize: 7
      },
      {
        id: "label-dongia",
        type: "text",
        x: 10,
        y: -13,
        width: 14,
        height: 3.5,
        content: "ĐƠN GIÁ",
        fontSize: 6,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#DC2626",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "val-dongia",
        type: "text",
        x: 10,
        y: -8.5,
        width: 14,
        height: 4,
        content: "105.000",
        fontSize: 9,
        fontWeight: "bold",
        fontFamily: "JetBrains Mono",
        textAlign: "center",
        excelColumn: "Giá bán",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "label-soluong",
        type: "text",
        x: 25,
        y: -13,
        width: 12,
        height: 3.5,
        content: "SỐ LƯỢNG",
        fontSize: 6,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#DC2626",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "val-soluong",
        type: "text",
        x: 25,
        y: -8.5,
        width: 12,
        height: 4,
        content: "1 cái",
        fontSize: 9,
        fontWeight: "bold",
        fontFamily: "JetBrains Mono",
        textAlign: "center",
        excelColumn: "Số lượng",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "label-thanhtien",
        type: "text",
        x: 16,
        y: -4,
        width: 27,
        height: 4,
        content: "THÀNH TIỀN",
        fontSize: 8,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#DC2626",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "val-thanhtien",
        type: "text",
        x: 16,
        y: 0,
        width: 27,
        height: 5,
        content: "105.000",
        fontSize: 12,
        fontWeight: "bold",
        fontFamily: "JetBrains Mono",
        color: "#000000",
        textAlign: "center",
        excelColumn: "Thành tiền",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "label-packed",
        type: "text",
        x: -22,
        y: 6,
        width: 18,
        height: 3,
        content: "NGÀY ĐÓNG GÓI",
        fontSize: 6,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#DC2626",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "val-packed",
        type: "text",
        x: -21,
        y: 10,
        width: 18,
        height: 3.5,
        content: "21/04/12",
        fontSize: 8,
        fontFamily: "JetBrains Mono",
        textAlign: "center",
        excelColumn: "Ngày đóng gói",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "label-expiry",
        type: "text",
        x: -3,
        y: 6,
        width: 19,
        height: 3,
        content: "NGÀY HẾT HẠN",
        fontSize: 6,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#DC2626",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "val-expiry",
        type: "text",
        x: -3,
        y: 10,
        width: 18,
        height: 3.5,
        content: "21/04/12",
        fontSize: 8,
        fontFamily: "JetBrains Mono",
        textAlign: "center",
        excelColumn: "Ngày hết hạn",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "label-storage",
        type: "text",
        x: 19,
        y: 6,
        width: 25,
        height: 3,
        content: "NHIỆT ĐỘ BẢO QUẢN",
        fontSize: 6,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#DC2626",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "val-storage",
        type: "text",
        x: 20,
        y: 10,
        width: 22,
        height: 3.5,
        content: "-18 đến -15 °C",
        fontSize: 7.5,
        fontWeight: "bold",
        fontFamily: "Inter",
        textAlign: "center",
        excelColumn: "Nhiệt độ",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "brand-logo",
        type: "text",
        x: -22,
        y: 17,
        width: 18,
        height: 6,
        content: "KiotViet",
        fontSize: 12,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#0000FF",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "banner-msg",
        type: "text",
        x: 11,
        y: 17,
        width: 38,
        height: 4,
        content: "TƯƠI NGON MỖI NGÀY",
        fontSize: 9,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#00B63E",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      }
    ]
  },
  {
    name: "Tem nhãn sản phẩm KM ( cuộn 2 tem )",
    description: "Mẫu tem quảng cáo, khuyến mãi có kích thước 35x22mm bao gồm tên cửa hàng, tên mặt hàng, mã vạch, giá niêm yết có gạch ngang và giá khuyến mãi nổi bật.",
    config: {
      width: 35,
      height: 22,
      name: "Cấu hình tự chọn",
      bgColor: "#ffffff"
    },
    sheetConfig: {
      mode: "thermal",
      cols: 2,
      rows: 8,
      rowGap: 3,
      colGap: 0,
      rollSideMargin: 1
    },
    objects: [
      {
        id: "init-text-1",
        type: "text",
        x: 0,
        y: -9,
        width: 31,
        height: 2.6,
        content: "CỬA HÀNG ĐIỆN TỬ VIỆT NAM",
        fontSize: 4.5,
        fontWeight: "bold",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "init-barcode-1",
        type: "barcode",
        x: -11,
        y: -4,
        width: 20,
        height: 7,
        content: "SP0000001",
        barcodeFormat: "CODE128",
        displayValue: true,
        barcodeWidth: 1.4,
        barcodeHeight: 11,
        textFlowOrigin: "center",
        barcodeTextMargin: 0.1,
        barcodeFontSize: 5.5,
        isCenterRelative: true
      },
      {
        id: "init-text-2",
        type: "text",
        x: -1,
        y: -6,
        width: 31,
        height: 2.6,
        content: "Ổ cắm LIOA",
        fontSize: 5,
        textAlign: "center",
        fontWeight: "bold",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "text-1780993278403",
        type: "text",
        x: 0,
        y: 5,
        width: 34,
        height: 3,
        content: "150.000 VNĐ",
        fontSize: 6.5,
        fontWeight: "normal",
        textAlign: "center",
        textDecorationLineThrough: true,
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "text-1780993317539",
        type: "text",
        x: 0,
        y: 8,
        width: 33,
        height: 3,
        content: "130.000 VNĐ",
        fontSize: 7,
        fontWeight: "bold",
        textAlign: "center",
        prefixText: "KM: ",
        prefixFontWeight: "bold",
        isCenterRelative: true,
        textFlowOrigin: "center"
      }
    ]
  },
  {
    name: "Tem nhãn sản phẩm KM ( Cuộn 3 tem )",
    description: "Mẫu tem quảng cáo, khuyến mãi dạng cuộn 3 tem/hàng có kích thước 35x22mm bao gồm tên cửa hàng, tên mặt hàng, mã vạch, giá niêm yết gạch ngang và giá KM nổi bật.",
    config: {
      width: 35,
      height: 22,
      name: "Cấu hình tự chọn",
      bgColor: "#ffffff"
    },
    sheetConfig: {
      mode: "thermal",
      paperSize: "A4",
      customWidth: 210,
      customHeight: 297,
      orientation: "portrait",
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 10,
      marginRight: 10,
      rows: 8,
      cols: 3,
      rowGap: 3,
      colGap: 0,
      showBorder: false,
      borderWidth: 1,
      borderRadius: 2,
      borderColor: "#9ca3af",
      rollSideMargin: 1
    },
    objects: [
      {
        id: "init-text-1",
        type: "text",
        x: 0,
        y: -9,
        width: 31,
        height: 2.6,
        content: "CỬA HÀNG ĐIỆN TỬ VIỆT NAM",
        fontSize: 4.5,
        fontWeight: "bold",
        textAlign: "center",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "init-barcode-1",
        type: "barcode",
        x: -11,
        y: -4,
        width: 20,
        height: 7,
        content: "SP0000001",
        barcodeFormat: "CODE128",
        displayValue: true,
        barcodeWidth: 1.4,
        barcodeHeight: 11,
        textFlowOrigin: "center",
        barcodeTextMargin: 0.1,
        barcodeFontSize: 5.5,
        isCenterRelative: true
      },
      {
        id: "init-text-2",
        type: "text",
        x: -1,
        y: -6,
        width: 31,
        height: 2.6,
        content: "Ổ cắm LIOA",
        fontSize: 5,
        textAlign: "center",
        fontWeight: "bold",
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "text-1780993278403",
        type: "text",
        x: 0,
        y: 5,
        width: 34,
        height: 3,
        content: "150.000 VNĐ",
        fontSize: 6.5,
        fontWeight: "normal",
        textAlign: "center",
        textDecorationLineThrough: true,
        isCenterRelative: true,
        textFlowOrigin: "center"
      },
      {
        id: "text-1780993317539",
        type: "text",
        x: 0,
        y: 8,
        width: 33,
        height: 3,
        content: "130.000 VNĐ",
        fontSize: 7,
        fontWeight: "bold",
        textAlign: "center",
        prefixText: "KM: ",
        prefixFontWeight: "bold",
        isCenterRelative: true,
        textFlowOrigin: "center"
      }
    ]
  },
  {
    name: "Tem mắt kính chữ T 40x28 đuôi 45",
    description: "Mẫu tem nhãn mắt kính chữ T tiêu chuẩn 40x28mm đuôi 45mm (tổng sải cánh 85mm), xoay đứng 90/270 độ tiện lợi dán gọng kính.",
    config: {
      width: 85,
      height: 28,
      name: "Cấu hình tự chọn",
      bgColor: "#ffffff"
    },
    sheetConfig: {
      mode: "thermal",
      paperSize: "A4",
      customWidth: 210,
      customHeight: 297,
      orientation: "portrait",
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 10,
      marginRight: 10,
      rows: 8,
      cols: 1,
      rowGap: 3,
      colGap: 0,
      showBorder: false,
      borderWidth: 1,
      borderRadius: 2,
      borderColor: "#9ca3af",
      rollSideMargin: 1
    },
    objects: [
      {
        id: "shape-1781017506767",
        type: "shape",
        x: 6,
        y: 12.5,
        width: 28,
        height: 3,
        content: "Đường kẻ",
        shapeType: "line",
        shapeStrokeWidth: 0.2,
        shapeStrokeColor: "#000000",
        shapeFillColor: "transparent",
        shapeCornerRadius: 0,
        shapeStrokeStyle: "solid",
        angle: 90
      },
      {
        id: "text-1781017572623",
        type: "text",
        x: -10,
        y: 11.5,
        width: 26,
        height: 3,
        content: "Mắt kính KiotShop",
        fontSize: 8,
        fontWeight: "bold",
        textAlign: "center",
        angle: 270
      },
      {
        id: "text-pasted-1781017927394-592-0",
        type: "text",
        x: 22,
        y: 12,
        width: 29,
        height: 3,
        content: "Mắt kính Rayban",
        fontSize: 8,
        fontWeight: "bold",
        textAlign: "center",
        angle: 90
      },
      {
        id: "barcode-1781018912670",
        type: "barcode",
        x: 0,
        y: 9,
        width: 19,
        height: 9,
        content: "SP-2026-A1",
        barcodeFormat: "CODE128",
        displayValue: true,
        barcodeWidth: 1.5,
        barcodeHeight: 15,
        textFlowOrigin: "center",
        angle: 270
      },
      {
        id: "text-pasted-1781018944642-160-0",
        type: "text",
        x: 2,
        y: 12,
        width: 29,
        height: 3,
        content: "1.500.000",
        fontSize: 8,
        fontWeight: "normal",
        textAlign: "center",
        angle: 270,
        prefixText: "Giá: ",
        suffixText: " VNĐ"
      },
      {
        id: "text-pasted-1781018949732-68-0",
        type: "text",
        x: 18,
        y: 11,
        width: 25,
        height: 3,
        content: "Oval",
        fontSize: 8,
        fontWeight: "normal",
        textAlign: "center",
        angle: 90,
        prefixText: "Kiểu: "
      },
      {
        id: "text-pasted-1781018959166-456-0",
        type: "text",
        x: 10,
        y: 12,
        width: 29,
        height: 3,
        content: "48-17-130",
        fontSize: 8,
        fontWeight: "normal",
        textAlign: "center",
        angle: 90,
        prefixText: "Size: "
      }
    ]
  },
  {
    name: "Tem mắt kính chữ T 50x35 đuôi 35",
    description: "Mẫu tem nhãn mắt kính chữ T tiêu chuẩn 50x35mm đuôi 35mm (tổng sải cánh 85mm), xoay đứng 90/270 độ dán gọng kính chuyên nghiệp.",
    config: {
      width: 85,
      height: 35,
      name: "Cấu hình tự chọn",
      bgColor: "#ffffff"
    },
    sheetConfig: {
      mode: "thermal",
      paperSize: "A4",
      customWidth: 210,
      customHeight: 297,
      orientation: "portrait",
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 10,
      marginRight: 10,
      rows: 8,
      cols: 1,
      rowGap: 3,
      colGap: 0,
      showBorder: false,
      borderWidth: 1,
      borderRadius: 2,
      borderColor: "#9ca3af",
      rollSideMargin: 1
    },
    objects: [
      {
        id: "shape-1781017506767",
        type: "shape",
        x: 11,
        y: 16,
        width: 28,
        height: 3,
        content: "Đường kẻ",
        shapeType: "line",
        shapeStrokeWidth: 0.2,
        shapeStrokeColor: "#000000",
        shapeFillColor: "transparent",
        shapeCornerRadius: 0,
        shapeStrokeStyle: "solid",
        angle: 90
      },
      {
        id: "text-1781017572623",
        type: "text",
        x: -10,
        y: 15,
        width: 26,
        height: 3,
        content: "Mắt kính KiotShop",
        fontSize: 8,
        fontWeight: "bold",
        textAlign: "center",
        angle: 270
      },
      {
        id: "text-pasted-1781017927394-592-0",
        type: "text",
        x: 33,
        y: 15,
        width: 29,
        height: 3,
        content: "Mắt kính Rayban",
        fontSize: 8,
        fontWeight: "bold",
        textAlign: "center",
        angle: 90
      },
      {
        id: "barcode-1781018912670",
        type: "barcode",
        x: 6,
        y: 12,
        width: 19,
        height: 10,
        content: "SP-2026-A1",
        barcodeFormat: "CODE128",
        displayValue: true,
        barcodeWidth: 1.5,
        barcodeHeight: 15,
        textFlowOrigin: "center",
        angle: 270
      },
      {
        id: "text-pasted-1781018944642-160-0",
        type: "text",
        x: 9,
        y: 15,
        width: 27,
        height: 3,
        content: "1.500.000",
        fontSize: 8,
        fontWeight: "normal",
        textAlign: "center",
        angle: 270,
        prefixText: "Giá: ",
        suffixText: " VNĐ"
      },
      {
        id: "text-pasted-1781018949732-68-0",
        type: "text",
        x: 30,
        y: 14,
        width: 25,
        height: 3,
        content: "Oval",
        fontSize: 7.5,
        fontWeight: "normal",
        textAlign: "center",
        angle: 90,
        prefixText: "Kiểu: "
      },
      {
        id: "text-pasted-1781018959166-456-0",
        type: "text",
        x: 13,
        y: 15,
        width: 29,
        height: 3,
        content: "48-17-130",
        fontSize: 7.5,
        fontWeight: "normal",
        textAlign: "center",
        angle: 90,
        prefixText: "Size: "
      },
      {
        id: "text-pasted-1781020737440-726-0",
        type: "text",
        x: -8,
        y: 15,
        width: 29,
        height: 3,
        content: "1B Yết Kiêu P. Cửa Nam, HN",
        fontSize: 5.5,
        fontWeight: "normal",
        textAlign: "center",
        angle: 270,
        prefixText: "",
        suffixText: ""
      },
      {
        id: "text-pasted-1781020916342-770-0",
        type: "text",
        x: 20,
        y: 14,
        width: 25,
        height: 3,
        content: "Bạc",
        fontSize: 7.5,
        fontWeight: "normal",
        textAlign: "center",
        angle: 90,
        prefixText: "Màu: "
      },
      {
        id: "text-pasted-1781020957818-275-0",
        type: "text",
        x: 25,
        y: 14,
        width: 25,
        height: 3,
        content: "Nhựa",
        fontSize: 7.5,
        fontWeight: "normal",
        textAlign: "center",
        angle: 90,
        prefixText: "CL: "
      }
    ]
  },
  {
    name: "Tem trang sức 75x10",
    description: "Mẫu tem trang sức có râu treo tiêu chuẩn 75x10mm bao gồm tên hàng hóa, giá bán, barcode và tên cửa hàng.",
    config: {
      width: 75,
      height: 10,
      name: "Cấu hình tự chọn",
      bgColor: "#ffffff"
    },
    sheetConfig: {
      mode: "thermal",
      paperSize: "A4",
      customWidth: 210,
      customHeight: 297,
      orientation: "portrait",
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 10,
      marginRight: 10,
      rows: 8,
      cols: 1,
      rowGap: 3,
      colGap: 0,
      showBorder: false,
      borderWidth: 1,
      borderRadius: 2,
      borderColor: "#9ca2af",
      rollSideMargin: 1
    },
    objects: [
      {
        id: "text-1781059440043",
        type: "text",
        x: 2,
        y: 0,
        width: 15,
        height: 4,
        content: "Tên hàng hóa",
        fontSize: 6,
        fontWeight: "normal",
        textAlign: "center"
      },
      {
        id: "text-pasted-1781059492802-234-0",
        type: "text",
        x: 2,
        y: 5,
        width: 15,
        height: 4,
        content: "Giá: ",
        fontSize: 6,
        fontWeight: "normal",
        textAlign: "center"
      },
      {
        id: "text-1781059523322",
        type: "text",
        x: 19,
        y: 0,
        width: 22,
        height: 4,
        content: "Tên cửa hàng",
        fontSize: 7,
        fontWeight: "normal",
        textAlign: "center"
      },
      {
        id: "barcode-17810595503398",
        type: "barcode",
        x: 21,
        y: 4,
        width: 19,
        height: 6,
        content: "SP-2026-A1",
        barcodeFormat: "CODE128",
        displayValue: true,
        barcodeWidth: 1.5,
        barcodeHeight: 10,
        textFlowOrigin: "center",
        barcodeFontSize: 5,
        barcodeTextMargin: 0
      }
    ]
  },
  {
    name: "Tem trang sức 85x12",
    description: "Mẫu tem trang sức có râu treo tiêu chuẩn 85x12mm bao gồm tên hàng hóa, giá bán, barcode và tên cửa hàng.",
    config: {
      width: 85,
      height: 12,
      name: "Cấu hình tự chọn",
      bgColor: "#ffffff"
    },
    sheetConfig: {
      mode: "thermal",
      paperSize: "A4",
      customWidth: 210,
      customHeight: 297,
      orientation: "portrait",
      marginTop: 10,
      marginBottom: 10,
      marginLeft: 10,
      marginRight: 10,
      rows: 8,
      cols: 1,
      rowGap: 3,
      colGap: 0,
      showBorder: false,
      borderWidth: 1,
      borderRadius: 2,
      borderColor: "#9ca2af",
      rollSideMargin: 1
    },
    objects: [
      {
        id: "text-1781059440043",
        type: "text",
        x: 4,
        y: 1,
        width: 19,
        height: 4,
        content: "Tên hàng hóa",
        fontSize: 8,
        fontWeight: "normal",
        textAlign: "center"
      },
      {
        id: "text-pasted-1781059492802-234-0",
        type: "text",
        x: 6,
        y: 6,
        width: 15,
        height: 4,
        content: "Giá: ",
        fontSize: 8,
        fontWeight: "normal",
        textAlign: "center"
      },
      {
        id: "text-1781059523322",
        type: "text",
        x: 26,
        y: 0,
        width: 22,
        height: 4,
        content: "Tên cửa hàng",
        fontSize: 9,
        fontWeight: "normal",
        textAlign: "center"
      },
      {
        id: "barcode-17810595503398",
        type: "barcode",
        x: 28,
        y: 5,
        width: 19,
        height: 6,
        content: "SP-2026-A1",
        barcodeFormat: "CODE128",
        displayValue: true,
        barcodeWidth: 1.5,
        barcodeHeight: 13,
        textFlowOrigin: "center",
        barcodeFontSize: 5,
        barcodeTextMargin: 0
      }
    ]
  }
];
